### PR TITLE
Fix exception on Ruby 3.1

### PR DESCRIPTION
**Pull request by feliperaul**
Without the `permitted_classes` param, backups will fail as of Ruby 3.1.

The offending line will try to load `yaml_file`, which will be something like `Backup/.data/database/S3.yml`. That file contains a YAML like this:

```
- !ruby/object:Backup::Package
  trigger: database
  extension: tar
  chunk_suffixes: []
  no_cycle: false
  version: 5.0.0.beta.2
  time: 2022.03.21.08.00.03
```

It seems as of Ruby 3.1, Psych will only deserialize classes that have been whitelisted. See [here](https://stackoverflow.com/questions/71332602/upgrading-to-ruby-3-1-causes-psychdisallowedclass-exception-when-using-yaml-lo).

Before this fix, the gem would throw this exception at that line:

```
[info] Storing '/home/deploy/backups/database/2022.03.28.11.15.46/database.tar'...
[info] Cycling Started...
[error] Tried to load unspecified class: Backup::Package
...
[error] Model::Error: Backup for Backup do database em server
[error] --- Wrapped Exception ---
[error] Psych::DisallowedClass: Tried to load unspecified class: Backup::Package
[error]
[error] Backtrace:
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:424:in `resolve_class'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `block in register_empty'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `each'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `register_empty'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:370:in `load'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:670:in `open'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:670:in `load_file'
[error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.2/lib/backup/storage/cycler.rb:55:in `yaml_load'
```

### CODE REVIEW

**Comment by elthariel** [comment]
Damn, I need to fix this damn travis-ci.
This LGTM though

**Comment by elthariel** [comment]
Hum. Looking a little bit more into your issue, I don't think those type metadata should be serialized in the first place. This isn't a part of the code I've worked with yet, but we should probably avoid using this kind of annotations for a variety of reasons:
- they can lead to security issues (hence the error you're encountering)
- they make the code harder to refactor
- the yaml file is less readable.

Do you happen to know if ruby 3.1 changes the behavior or the serializer (i.e. do you know if the file was produced with those annotations before ruby 3.1?)

**Comment by feliperaul** [comment]
Hi! Unfortunately no. This was just a quick fix to make the gem work with ruby 3.1.

**Comment by elthariel** [comment]
As you can imagine, I'd rather have someone (you ? <3) look a tiny bit deeper into the issue before merging a fix :)
Do you think you can find the time to trace the origin of that file and if the behavior is expected ?

**Comment by betmenslido** [comment]
>>  do you know if the file was produced with those annotations before ruby 3.1?
Before 3.1 deserialization was produced with those anotations. All classes were allowed for deserialization.

>> the yaml file is less readable.
I checked with ruby 2.7.5 and backup 5.0.0.beta.3. Yaml file, as expected, contains entries of "Backup::Package", meaning there are no changes in yaml serialization in 3.1+, at least in regard to this use case.

**Comment by elthariel** [comment]
I've migrated the CI to github actions, as travis-ci.org is now dead, you can see the results of the lint and specs.

Your tests convinced me this was the proper approach to fix the issue, that being said, the implementation in #979 is slightly more robust, despite still failing the specs :D.

Feel free to fix this other PR, or to wait for it to be fixed and merged

**Comment by elthariel** [comment]
In all cases, I'd like to thank you for your PR and subsequent tests, which helped me understand how it was a good approach to fix the issue :+1:

**Comment by talhajunaid63** [comment]
Hi @elthariel @feliperaul Thank you for great work. I am still facing this issue with `5.0.0.beta.3` and `ruby 3.1.0`. I am storing the backup on `Local`.

Here is the log

```
[2022/12/21 13:23:50][error] Model::Error: Backup for Description for production_backup (production_backup) Failed!
[2022/12/21 13:23:50][error] --- Wrapped Exception ---
[2022/12/21 13:23:50][error] Psych::DisallowedClass: Tried to load unspecified class: Backup::Package
[2022/12/21 13:23:50][error] 
[2022/12/21 13:23:50][error] Backtrace:
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:424:in `resolve_class'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `block in register_empty'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `each'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `register_empty'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:370:in `load'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:670:in `open'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:670:in `load_file'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/storage/cycler.rb:55:in `yaml_load'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/storage/cycler.rb:14:in `cycle!'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/storage/base.rb:45:in `perform!'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/model.rb:329:in `block in store!'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/model.rb:327:in `map'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/model.rb:327:in `store!'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/model.rb:301:in `block in procedures'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/model.rb:267:in `block in perform!'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/model.rb:266:in `each'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/model.rb:266:in `perform!'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/lib/backup/cli.rb:155:in `perform'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/backup-5.0.0.beta.3/bin/backup:5:in `<top (required)>'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/bin/backup:25:in `load'
[2022/12/21 13:23:50][error]   /home/deploy/.rbenv/versions/3.1.1/bin/backup:25:in `<main>'
```

Here is my production_backup.rb file

```ruby
# encoding: utf-8

##
# Backup Generated: production_backup
# Once configured, you can run the backup with the following command:
#
# $ backup perform -t production_backup [-c <path_to_configuration_file>]
#
# For more information about Backup's components, see the documentation at:
# http://backup.github.io/backup
#
Model.new(:production_backup, 'Description for production_backup') do
  database PostgreSQL do |db|
    # To dump all databases, set `db.name = :all` (or leave blank)
    db.name               = "databasename"
    db.username           = "abc"
    db.password           = "abc"
    db.host               = "localhost"
    db.port               = 5432
    db.socket             = "/var/run/postgresql"
  end

  store_with Local do |local|
    local.path = '~/backups/'
    # Use a number or a Time object to specify how many backups to keep.
    local.keep = 5
  end
end
```

**Comment by cbarratt** [comment]
I'm also seeing this error still Ruby 3.2.0 / 5.0.0.beta.3

**Pull request closed without merging**
