### PR TITLE
Use RuboCop to enforce code style guidelines

### LINKED ISSUE #805: Use a Ruby style guide
Use Rubocop for style guide control.

I still have the config from my last (proprietary) project that we can use as a basis.

Rubocop also offers an auto-fix for existing code and can generate a TODO set of rules that will still have to be fixed afterward.

### PR DESCRIPTION
**Pull request by tombruijn**
Closes #805

### CODE REVIEW

**Comment by tombruijn** [comment]
There are quite a few errors being thrown. That's good! I've already found some problem areas that we might need to look at if we want to improve the inner workings of Backup. (For example: why is backup [manipulating a constant?](https://github.com/backup/backup/blob/907a744733a4e56ea89f5e4638f43120beefb68f/lib/backup/utilities.rb#L36))

@stuartellis what do you think of this code style? Look at the `.rubocop.yml` file for the new standard. You can read more about rubocop here: http://rubocop.readthedocs.io/en/latest/

I don't think we need to merge a major autocorrect run like this. It's just for demonstration purposes to see what the new ruleset would mean in terms of codes style.

We can generate a `.rubocop_todo.yml` file that lists all the rules that need to be fixed while allowing rubocop to run successfully in the CI. Then we can fix the rubocop violations one by one in separate PRs and discuss the fine details about certains rules there.

**Comment by stuartellis** [comment]
@tombruijn That sounds like a good plan to me.

I've read the .rubocop.yml, and the other commit, and it looks OK to me. My personal preference is to use single quotes except where there's interpolation, but that probably seems pedantic, so it might be easier to just standardize on double quotes everywhere.

The only other comment is that the .rubocop.yml currently specifies "TargetRubyVersion: 2.0": we may want to explicitly use "TargetRubyVersion: 2.3".

**Comment by tombruijn** [comment]
> My personal preference is to use single quotes except where there's interpolation, but that probably seems pedantic, so it might be easier to just standardize on double quotes everywhere.

ah the good old war against single and double quotes. I haven't found a particular useful case for mixed quotes as you say. I usually introduce the idea of using `%(i'm a "string")` to the argument :)

Anyhow.. Most languages use double quotes for strings and single quotes for characters. Why would Ruby be different just because it support strings with single quotes?

> The only other comment is that the .rubocop.yml currently specifies "TargetRubyVersion: 2.0": we may want to explicitly use "TargetRubyVersion: 2.3".

Since we support Ruby 2.0 and higher I set it to version 2.0. We shouldn't be using that were only introduced in Ruby 2.3 and higher. Rubocop should warn us about that this way.

**Comment by tombruijn** [comment]
Alright. Updated this PR so it's no longer failing. Kept a couple violations in which are registered in the `rubocop_todo.yml` file and thus ignored. Those are a little bit more complex to fix, which can be done at a later time while upgrading RSpec and other gem dependencies.

The PR basically changes all the files updating syntax and enforcing one code style. It will screw up the git blame a bit, but will give us a lot more focus in writing one type of style. Also easier for new contributors. 

Do you agree we can merge this @stuartellis and fix the as we go along?

**Comment by stuartellis** [comment]
Yes @tombruijn, I think that it would be great to merge this. It's a lot of churn, but the individual changes seem safe, and I think that it's worth it to get the code consistent.

**Pull request merged**
