### PR TITLE
update twitter to 5.16 and http to 1.0 fixes security issue

### PR DESCRIPTION
**Pull request by mapopa**
https://github.com/sferik/twitter/issues/672

### CODE REVIEW

**Comment by tombruijn** [comment]
@mapopa Thanks for the PR! I saw I never pushed the commits belonging to v4.4.1. Sorry about that.

**Comment by tombruijn** [comment]
Looks like the build is failing on the public_suffix addition. It requires Ruby 2.1, so it fails on 2.0. I wouldn't want to drop 2.0 support without bumping a major version. Which is what v5 is for. Anyway way around this or can we not merge this fix?

**Comment by mapopa** [comment]
Support for 2.0 has ended https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

**Comment by mapopa** [comment]
In fact even 2.2 is EOL https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/

**Comment by tombruijn** [comment]
We shouldn't drop Ruby versions in minor/patch releases on the v4 branch. Only drop Ruby versions on the v5/master branch (next major version).
Would we still need to upgrade twitter here then if the build is unfixable?

**Pull request closed without merging**
