### PR TITLE
Fix some rubocop offenses

### PR DESCRIPTION
**Pull request by nlsrchtr**
I did some work on the rubocop offenses to bring down the numbers. Especially replacing ```should == ``` with ```should eq()``` and some other minor improvements.

Would be great to see this as a base to lower the offenses in this project.

### CODE REVIEW

**Comment by reedloden** [comment]
You accidentally included the #843 patch in this, FYI.

**Comment by nlsrchtr** [comment]
@reedloden thanks for pointing this out. I made a fork based on my feature branch, so my own code would also benefit from my rubocop work. If this is a blocker for you, just let me know and I'll try to make a plain "rubocop offenses" PR.

**Comment by tombruijn** [comment]
Hi @nlsrchtr, I'm not going to merge this PR, but merge these changes along the way in smaller PRs like #847.

Thanks for the PR anyway :)

**Comment by nlsrchtr** [comment]
@tombruijn ok, great. I hope the work will somehow add some value :-)

**Comment by tombruijn** [comment]
It will :)
This PR has highlighted some changes I want to merge and problem areas I want to fix. Some are already in #847 and #846

**Pull request closed without merging**
