### PR TITLE
Azure Storage

### PR DESCRIPTION
**Pull request by geronimo**
Implementation of a first working version of Azure as a storage, many missing parts (like Cycler) but it gets the basic storage work done.

Still implementing some specs, I just want to hear your comments.

### CODE REVIEW

**Comment by otzy007** [comment]
:+1: 
why not merge it? It works well.

**Comment by zx1986** [comment]
not merge yet?

**Comment by agalisteo** [comment]
not merge yet?

**Comment by tombruijn** [comment]
I  closed this due to inactivity. If anyone wants to pick this up and submit another PR, feel free to do so based on the latest master branch.

**Pull request closed without merging**
