### PR TITLE
Use modern gem dependency solution

### PR DESCRIPTION
**Pull request by tombruijn**
Drop old gem dependency management.

Was made before I came on board. I have no idea why it's setup like this, other than to be very strict about which versions are used for everything. But assuming everything is non breaking between minor versions I think we can do manage with this solution.

### CODE REVIEW

**Comment by stuartellis** [comment]
Looking into this a bit further, we it seems like we can move the development dependencies into the gemspec as well, and Bundler should do the right thing: http://bundler.io/rubygems.html. That would avoid splitting the dependencies between the gemspec and the Gemfile.

**Comment by tombruijn** [comment]
ah yes! I'll add development_dependencies to the gemspec. That works much nicer :)

**Comment by tombruijn** [comment]
Updated. I'll try to publish a alpha release tomorrow to see how it looks as a ru rubygem.

**Comment by tombruijn** [comment]
Alright.. That took some more work on the `publish` rake task. It wasn't very compatible with the new solution so I updated it.

**Comment by stuartellis** [comment]
OK, I've set this up on a clean installation of Ruby 2.3.3, and there's one Rubcop warning:

    Rakefile:42:18: W: Lint/UnneededDisable: Unnecessary disabling of Metrics/BlockLength.
    task :release do # rubocop:disable Metrics/BlockLength
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
From:

    git pull 8750597
    bundle install
    rake rubocop

**Comment by tombruijn** [comment]
I'm not getting that violation, neither is the build on Travis?

You're probably running an older version. I forced pushed some changes

**Comment by stuartellis** [comment]
That fixed it: commit df70849 runs without warnings.

**Comment by tombruijn** [comment]
Alright, great!

Then I think this PR is accepted. I want to use this new strategy for the next major version which contains changes now present on the `master` branch. Now that I think about it merging those on the master branch probably wasn't the best, but we don't have a develop branch right now.

I suggest all changes, like dropping ruby 2.0, that occurred after the version 4.4.0 should be considered the part of v5.

If we really need to fix anything in v4 we'd need to create a v4 branch from that point. Don't really want to do that now, so we'll use that strategy once the need arises.

I'll try to find some hours to update the things I'd want to see in v5 and add them to the "Next version" milestone I created. I'd probably most like to see a complete test suite (including the integration tests you're working on) for starters :)

Let me know if you agree and if we should discuss this further

**Comment by stuartellis** [comment]
That sounds like a good plan to me. We are effectively using the master branch for development  already, so it's just making that officially official.

If we can fix Ruby 2.4.0 support simply by bumping dependencies (as described in #820), I guess that there's an argument for a 4.5.0 release that has that one change and nothing else.

**Comment by tombruijn** [comment]
I'll see if I can fix #820 but looks like one of our deps doesn't allow upgrading json.

Will merge this change on master and create a separate branch for v4.x if the dep is updated before we release a new version.

**Pull request merged**
