### PR TITLE
Attempt all configured Storages, regardless of errors

### PR DESCRIPTION
**Pull request by tmikoss**
So that when one storage does not work, data has a chance of being stored elsewhere.

I had a recent experience, where backups configured to be stored via SCP and S3 storages were failing due to connection issues to SCP destination. Connection to S3 was still usable, but no backups were being made via that because SCP was attempted first, and failing.

### CODE REVIEW

**Comment by tombruijn** [comment]
Looks good! but I guess the only problem would be if you have more than one exception thrown? You can only rethrow one exception so the other(s) will be silently ignored, right?

**Comment by tmikoss** [comment]
Yes, that would be the case. I don't feel familiar enough with the code base to handle that - do you have any suggestions?

Maybe send any remaining exceptions to logger before re-raising the first one? Would preserve the information about what went wrong without altering the existing error handling process.

**Comment by tombruijn** [comment]
I think that's a good idea, to log every error except the first/last to `Logger.error`/`Logger.warn` and re-raise the first/last one to make backup exit.

Can you add this to this PR?

**Comment by tmikoss** [comment]
Will do.
2015. gada 18. jūl. 15:25, "Tom de Bruijn" <notifications@github.com>
rakstīja:

**Comment by tmikoss** [comment]
@tombruijn added logging of exceptions that don't get re-raised

**Comment by tombruijn** [comment]
@tmikoss thanks for the update! The only problem I see now is that the errors don't give a backtrace for their errors, only the exception that gets re-raised. So I think it would be best to also add the backtrace of the other errors.

That would become something like the diff below. What do you think?

```diff
diff --git a/lib/backup/model.rb b/lib/backup/model.rb
index 0bfca34..f54707d 100644
--- a/lib/backup/model.rb
+++ b/lib/backup/model.rb
@@ -340,7 +340,10 @@ module Backup
       first_exception, *other_exceptions = storage_results.select { |result| result.is_a? Exception }

       if first_exception
-        other_exceptions.each { |exception| Logger.error exception }
+        other_exceptions.each do |exception|
+          Logger.error exception.to_s
+          Logger.error exception.backtrace.join("\n")
+        end
         raise first_exception
       else
         true
```

**Comment by tmikoss** [comment]
Looks good!

**Comment by tombruijn** [comment]
Can you amend it to your last commit then? I'll merge it right after you update.

**Comment by tmikoss** [comment]
Done.

**Comment by tombruijn** [comment]
Great! Thanks!

**Pull request merged**
