### PR TITLE
Add Storage Qiniu

### PR DESCRIPTION
**Pull request by bastengao**
This adds a storage: "Qiniu".

As you kwon S3 is perfect,but unavailable in China, so we only find other solutions instead of it. [Qiniu](http://www.qiniu.com/) is one of most popular cloud storage services in China.

### CODE REVIEW

**Comment by hi54yt** [comment]
+1

**Comment by bastengao** [comment]
Hi @tombruijn, I really need this future. I'm happy to help if you have questions.

**Comment by tomash** [comment]
Looks decent in my opinion, but the regular `::Qiniu.establish_connection` looks a bit unnerving. Might be more readable and maintainable to have this "external" class method aliased/proxied inside `Storage::Qiniu` class.

**Comment by bastengao** [comment]
@tomash Thanks for your advice. I have already extracted `#config_credentials` method and pushed it.

**Comment by bastengao** [comment]
@tombruijn Any advice ?

**Comment by tombruijn** [comment]
Hi @bastengao, thanks for the PR!

The reason I've not answered this in a while is because I wasn't not entirely sure about merging it. I can't really tell what Qiniu does, as I can't read Chinese.

Not entirely sure with the additional secondary dependencies either. I know, it's a bit late to complain about that now 😓  So disregard that

I think that if rebased on the latest master branch we can merge this. So please rebase it so that I can merge it 👍

**Comment by bastengao** [comment]
@tombruijn Thanks for your response. I will do it later. 😄

**Comment by bastengao** [comment]
@tombruijn Rebased it.

**Comment by tombruijn** [comment]
Great! Merged it 😄

**Pull request merged**
