### PR TITLE
Deprecate certain Backup features

### LINKED ISSUE #851: Deprecations for v5
We need to deprecate some stuff because it's too hard to maintain for us now.

Some suggestions below. Let us know if you agree/disagree or use any of these.

These features will still be present in older versions of backup, =< v5, but going forward Backup will support less features that are not actively used.

## core features

- [x] Sudo option #853

## Databases

- [x] OpenLDAP #853
- [x] Riak #853

## Storages

- [x] Dropbox, v1 is being deprecated in June 2017. Only keep it if we support v2 before that
- [x] FTP #853
- [x] Ninefold, removed in #757 
- [x] Rackspace CloudFiles #853

## Syncers

- [x] All of them #853

## Notifiers 

- [x] Campfire #853
- [x] Nagios #853
- [x] Prowl #853
- [x] Twitter #853
- [x] Zabbix #853

### PR DESCRIPTION
**Pull request by tombruijn**
Deprecates Databases, syncers, storage and notifiers as listed in #851.

Example output:

```
[2017/04/23 14:20:59][warn] The Backup database "OpenLDAP" is scheduled to be deprecated. If you're using this feature, please see: https://github.com/backup/backup/issues/851
[2017/04/23 14:20:59][warn] The Backup syncer "Cloud::CloudFiles" is scheduled to be deprecated. If you're using this feature, please see: https://github.com/backup/backup/issues/851
```

Closes #851

### CODE REVIEW

**Comment by tombruijn** [comment]
Deprecated the sudo option by logging the warning when the `sudo` utility is used. 

Anyone care to review? Otherwise I'll merge this tomorrow

**Comment by reedloden** [comment]
I wish we had more data on which notifiers / features were actually used. Telemetry is great for these sorts of questions. We're basically just guessing right now. However, I guess once this gets pushed out, we'll get some feedback in #851.

Aside from that comment, the PR looks fine to me (and it passes test suite). My only technical concern is that you'd have an issue if you have the same module name in different things (like `S3` is technically both a storage and syncer module). Since we're deprecating all the syncers, I think that's fine, but something to note for the future.

**Comment by tombruijn** [comment]
> I wish we had more data on which notifiers / features were actually used. Telemetry is great for these sorts of questions. We're basically just guessing right now. However, I guess once this gets pushed out, we'll get some feedback in #851.

Some data about how much what is used would be nice, but it's probably a lot of work to build, and we'd really need to make sure such data is anonymized. I'm not against including/supporting things which are less used, as long as it doesn't weigh down backup in its entirety. Splitting support for things like s3 into separate (unofficial/non-core) gems would allow backup core to move forward a lot easier.

I'm just guessing here about what to deprecate, but I've also deprecated thing which, in my opinion, shouldn't be part of backup, such as the sudo option.

Version 4 isn't going anywhere though. If people need to keep using things I've deprecated here, they can continue using the older versions.

> Aside from that comment, the PR looks fine to me (and it passes test suite). My only technical concern is that you'd have an issue if you have the same module name in different things (like S3 is technically both a storage and syncer module). Since we're deprecating all the syncers, I think that's fine, but something to note for the future.

True. I've opted for the easy solution right now. I didn't want to over-engineer it and delay a release even more. This deprecation logic will be removed in its entirety in a next release.

**Comment by zaolin** [comment]
I think that is really really a bad idea. Dropping S3 syncing support leads to big issues regarding the asset backups. We are using the backup gem in production and offering our customers an asset package of 500GB. Therefore using normal S3 backup technology is too heavy for doing a backup. It takes too long and allocates massive resources.

**Comment by tombruijn** [comment]
@zaolin I already gave a bit of feedback on removing the syncer feature in https://github.com/backup/backup/issues/851#issuecomment-300273811, let's continue the discussion there.

**Pull request merged**
