### PR TITLE
#692 Fix incorrect success codes for tar command

### PR DESCRIPTION
**Pull request by pawelduda**
Fixes https://github.com/backup/backup/issues/692

### CODE REVIEW

**Comment by tombruijn** [comment]
Hi @pawelduda! I closed the issue, let's continue the conversation here.

I see what you mean. It's inconsistent behavior which might cause some problems. However, I cannot merge your PR right now. If you look at the TravisCI results you'll see that some specs are broken due to your change.

Can you please update the specs?

**Comment by pawelduda** [comment]
@tombruijn I should be able to find some time to update those specs sometime later this week

**Comment by pawelduda** [comment]
@tombruijn Should be ready to merge :+1:

**Comment by tombruijn** [comment]
This has been released in 4.2.0

**Pull request merged**
