### PR TITLE
[WIP] Strip down of external gem dependencies

### PR DESCRIPTION
**Pull request by tomash**
Mission: make backup modular for better maintainability. As shown, external gem dependencies can slow us down, including to a point where it's not possible to make `backup` compatible with Ruby 3+ as long as we have some of those dependencies.

Approach: split `backup` into "core" (might rename it to `backup-core`) and plugins that add third-party integrations.

Progress: 
- [x] First blood: removed all external service integrations that require additional gems (tests green after all that deletion). This already gives us Ruby 3.2(.2) compatibility.
- [x] Removed `rubocop`, at least for now. Newer ruby versions mean newer rubocop, and newer rubocop means many renames, new cops and basically hundreds of offenses by current codebase.

### CODE REVIEW

**Comment by tombruijn** [comment]
I'm all for some kind of plugin system so that you don't need to load in 100 dependencies you don't need 👍

**Comment by elthariel** [comment]
We don't necessarily need to split this into multiple gems. What about removing the dependencies from the gem specifications, but instead performing a check when we load a file requiring a certain dependency ?

Smth like:

```ruby
begin
  require 'gem'
rescue LoadError
  puts "You need to install 'gem' to use this feature"
  exit(42)
end
```

I think the `autoload` stanzas will work with this approach, only triggering an error to the user if they use a certain feature.

We could still create a fake meta package `backup-all-deps`, or a subcommand that lists the relevent gems to install for each features, to make it easy for the user ?

**Comment by tomash** [comment]
@elthariel this is a very good idea in general.

The reason I took this specific approach -- separating core from integrations -- is because those integrations can prevent the entire gem from being compatible with new version of Ruby (for example, could also mean some other lib) as experienced in #1000 . The require-rescue approach does not solve that, as for our test suite to run successfully we need those integrations installed (and hindering our development) anyway.

**Comment by tomash** [comment]
Here's an example of integration gem, I've copypasted the code for Twitter notifier, so it's basically two files: notifier class and its spec (and two spec helpers for shared examples). Small, easy to navigate: https://github.com/tomash/backup-twitter

As a part of this effort I'll of course do that with other integrations removed from core gem.

**Comment by elthariel** [comment]
My initial reaction is that due to the change of pricing of the Twitter API, dropping support for it altogether is probably not too far fetched. Do you have other examples of this despite Twitter and oVirt ?

What would you think about taking a middle-ground approach:

- We select a list of modules that remains explicit dependencies of the `backup` gem.
- We select a list of modules where we implement the require/catch trick. 
  - We'd have to modify the pipelines a bit to install those deps to have our tests pass
  - We'd document the thing and print nice error messages to the user
- We select a list of module that we split into separate gems. Those would be the more *niche* dependencies and the one that we know will never get recent ruby support
  - We'd have to provide documentation and a convenient way to declare in your backup definition file that it depends on this other gem.
  
 
 All in all, I think this approach of splitting some modules into a separate gem make sense for some of the most annoying dependencies, and I also like that it'd be much easier for anyone to add it's own module when they need.
 
That being said, I think we can do it in a way that minimize impact, doesn't require a naming change and a major version bump ?

**Comment by tomash** [comment]
>Do you have other examples of this despite Twitter and oVirt?

No, only oVirt. But we only need one to block entire gem's compatibility with new versions.

>What would you think about taking a middle-ground approach:

I'm not against it.

This however will imply that an integration has been considered "bad" and therefore booted out to external gem, as opposed to "good" ones that remain built-in. As a counter-example, `fog` maintainers say openly to use specific fog integration gem instead of one with everything.

Which reminds me. `fog` use with backup should be also based on picking specific fog integrations instead of "umbrella" catch-all gem, at least given fog's maintainers' recommendation. So `backup` users will sooner or later have to become acquainted with compose-your-set ("a la carte") approach to installing and using `backup` anyway.

My main concern with middle-ground approach is future-proofing versus reacting. We extract a subset of integrations in reaction to poor state of the gems they use, which is reactive, and are still vulnerable if one of the other integration dependency becomes a blocker in the future, like oVirt has been recently. I'd rather root them all out as a part of single lift -- smaller cognitive load to extract 9 small gems now, with the boilerplate they share (shared examples) -- than do one-two every time we're blocked from forward compatibility again.

**Comment by tomash** [comment]
>That being said, I think we can do it in a way that minimize impact, doesn't require a naming change and a major version bump ?

You're right. This is a change to underlying architecture, and the way gem is used, but it's not a breaking change to any of the public APIs.

Also 5.0 stable still hasn't been published, we can piggyback on that and use 5.0 as the stable version (since everybody seems to be running on either `~> 4.5` or `= 5.0.0.betax`) after merging this overhaul.

**Comment by elthariel** [comment]
> My main concern with middle-ground approach is future-proofing versus reacting

Haha. Future-proofing is a fool's game. And we are reacting (albeit very late) to fog's recommendation.

That being said, I buy your arguments, you convinced me :)

Circling back to the case of twitter and oVirt, I think we'll eventually drop support for old ruby versions (let's not define *old* at the moment), which means we'll eventually have to drop support for those providers. So maybe we should just drop them right now ? If not, we're already going to have a two tiered system, the providers supporting recent rubies and the others...

I'm still a little bit concerned about the amount of work involved, especially regarding managing the CI and the deployment  of the multiple gems.

What's your take on testing and versioning ? What would be the versioning of those gems, how would it related to the version of the main gem ? How would you proceed to test these together ? What about selecting which versions to test ?

Maybe we should produce most of those gems from the current repository, it'll be much easier to test and release, while still allowing and documenting how to integrate external gems. That still means a two tiered system with *less supported* gems booted to external repos, but we'd get a leaner core system, more modular deps, support for newer rubies and a documented, easier way to add new providers for external users.

**Comment by tomash** [comment]
>Future-proofing is a fool's game.

I did not mean future-proofing as in "no work will be required", I meant being more future-ready, to be less broken by future changes and make it easier to react. As in, main selling points of good architecture ;) 

>which means we'll eventually have to drop support for those providers

To clarify things a bit:
* twitter notifier works, I just used this integration as example as it was very easy to extract
* ovirt-sdk fix is merged and released with ovirt 4.6.0 and also `fog` is used only for S3 storage, so I'll see if just switching to `fog-aws` will make the build problems go away

>What's your take on testing and versioning ?

We went through this with `globalize` (as it plugged into ActiveRecord internals which changed with every major version) and together with other maintainers concluded that the best approach would be to follow the main dependency's version, at least on the major number level. So if we release this modularity in Backup 5.0, then integration gems should have version 5.x.y (and a dependency on backup `~> 5.0` of course). This addressess all concerns in pretty elegant way.

>Maybe we should produce most of those gems from the current repository, it'll be much easier to test and release, while still allowing and documenting how to integrate external gems.

Works for me, agreeing with all your points in this regard. Which subdir, classic `vendor/` or more semantic `integrations/`?

**Comment by elthariel** [comment]
>  As in, main selling points of good architecture ;)

Don't worry, I was just kidding :)

> To clarify things a bit

Thanks !

>  So if we release this modularity in Backup 5.0, then integration gems should have version 5.x.y (and a dependency on backup ~> 5.0 of course). This addresses all concerns in pretty elegant way.

Sold ! 

> Which subdir, classic vendor/ or more semantic integrations/?

TBH, I'd rather defer this choice to you. If you want my two cents, `vendor/` gives less of an impression of being maintained by the same team so I'd hint towards `integrations/` :shrug:

**Comment by elthariel** [comment]
On an unrelated note, allow me to mention that as per [our contribution rules](https://github.com/backup/backup/blob/master/CONTRIBUTING.md#becoming-a-committer), if you implement this, I'll happily add you as a committer on this repo

**Comment by tomash** [comment]
@elthariel thanks. [I was a commiter many years ago](https://github.com/backup/backup/commits/master/?author=tomash) :D 

For sake of more effective discussion of this effort and approach, we're exchanging some messages with @tombruijn and would like to have an email thread. I don't have your address, can you ping me on t.stachewicz@gmail.com?

**Comment by tomash** [comment]
Closing in favor of #1004

**Pull request closed without merging**
