### PR TITLE
use dropbox-sdk in newest 1.6.5 version

### LINKED ISSUE #762: It is necessary to update dropbox-sdk version
I have received the letter from api-support@dropbox.com

> We're writing to you because our logs indicate that you have at least one Dropbox API app using an old version of the Ruby Core SDK, with an out of date certificate file. 
> 
> The Dropbox Ruby Core SDK implements certificate pinning, based on a list of certificates included in the SDK, in order to help secure the connection to the Dropbox API servers.
> 
> On August 1st, 2016, the Dropbox API servers will be updated to use a new certificate, so you’ll need to update the version of the SDK used in your app to match. The latest version of the Ruby Core SDK already contains the updated certificate file:
> 
> [https://www.dropbox.com/developers-v1/core/sdks/ruby](https://www.dropbox.com/developers-v1/core/sdks/ruby)
> 
> You can refer to the CHANGELOG file included in the SDK for a list of changes.
> 
> Please update your app to use the latest SDK by 8/1/16 to ensure continued access to the Dropbox API.

### PR DESCRIPTION
**Pull request by tomash**
caused by #762.
Closes #762 

tests pass, needs some more testing in the wild.

### CODE REVIEW

**Comment by tomash** [comment]
Confirmed it works for @must-not-code in #762 .

**Comment by tombruijn** [comment]
Hey @tomash, good to see you again! Thanks for the PR

Is the client patch still required? If so, shall we leave the `# patched` comment in the Gemfile?

**Comment by tomash** [comment]
It doesn't seem necessary, I've just used "stock" 1.6.5. Is there a test to ensure that patch is no longer necessary and we won't introduce a regression?

Yes, it's good to be back in opensource :)

**Comment by tombruijn** [comment]
I don't think there's a test for the patch. This looks to me like the patch:  https://github.com/backup/backup/blob/34feab1a156295f9c19bda2c5c85ffefa2be396e/lib/backup/storage/dropbox.rb#L214-L236
DropboxClient::ChunkedUploader, but I'm not sure what we're doing extra here next to the normal chunkeduploader. Maybe we should remove it and see if it breaks any edge cases?

**Comment by tomash** [comment]
Code dump ahead comparing dropbox-sdk 1.5.1, backup's patch and current dropbox-sdk 1.6.5:

```ruby
# 1.5.1:
# no url since I don't know where's the repository for <1.6.4 versions,
# did a gem install and gem open to see this

def upload(chunk_size=4*1024*1024)
  last_chunk = nil

  while @offset < @total_size
    if not last_chunk
      last_chunk = @file_obj.read(chunk_size)
    end

    resp = {}
    begin
      resp = @client.parse_response(@client.partial_chunked_upload(last_chunk, @upload_id, @offset))
      last_chunk = nil
    rescue DropboxError => e
      resp = JSON.parse(e.http_response.body)
      raise unless resp.has_key? 'offset'
    end

    if resp.has_key? 'offset' and resp['offset'] > @offset
      @offset += (resp['offset'] - @offset) if resp['offset']
      last_chunk = nil
    end
    @upload_id = resp['upload_id'] if resp['upload_id']
  end
end


# backup's patch:
# https://github.com/backup/backup/blob/34feab1a156295f9c19bda2c5c85ffefa2be396e/lib/backup/storage/dropbox.rb#L214-L236
# rationale:
# https://github.com/backup/backup/commit/8454205339adf3f00dce2b01e2b05625fdaece48

def upload(chunk_size = 1024**2 * 4)
  while @offset < @total_size
    @file_obj.seek(@offset) unless @file_obj.pos == @offset
    data = @file_obj.read(chunk_size)

    begin
      resp = @client.parse_response(
        @client.partial_chunked_upload(data, @upload_id, @offset)
      )
    rescue DropboxError => err
      resp = JSON.parse(err.http_response.body) rescue {}
      raise err unless resp['offset']
    end

    @offset = resp['offset']
    @upload_id ||= resp['upload_id']
  end
end


# dropbox-sdk 1.6.5:
# https://github.com/dropbox/dropbox-sdk-ruby/blob/master/lib/dropbox_sdk.rb

def upload(chunk_size=4*1024*1024)
  last_chunk = nil

  while @offset < @total_size
    if not last_chunk
      last_chunk = @file_obj.read(chunk_size)
    end

    resp = {}
    begin
      resp = Dropbox::parse_response(@client.partial_chunked_upload(last_chunk, @upload_id, @offset))
      last_chunk = nil
    rescue SocketError => e
      raise e
    rescue SystemCallError => e
      raise e
    rescue DropboxError => e
      raise e if e.http_response.nil? or e.http_response.code[0] == '5'
      begin
        resp = JSON.parse(e.http_response.body)
        raise DropboxError.new('server response does not have offset key') unless resp.has_key? 'offset'
      rescue JSON::ParserError
        raise DropboxError.new("Unable to parse JSON response: #{e.http_response.body}")
      end
    end

    if resp.has_key? 'offset' and resp['offset'] > @offset
      @offset += (resp['offset'] - @offset) if resp['offset']
      last_chunk = nil
    end
    @upload_id = resp['upload_id'] if resp['upload_id']
  end
end

```

**Comment by tomash** [comment]
I haven't been witness to creation of backup's patch. Reading Brian's commit message and reading 1.6.5 code, it seems the new dropbox-sdk still has offset-setting code that Brian has modified in his patch. Not an expert on this one, though.

**Comment by tombruijn** [comment]
Unfortunately I don't know either the precise conditions that brought forth this patch.

I just ran a test backing up a directory of 30mb running backup from your branch without the patch and it succeeded. It didn't go in an "endless loop of PUT requests with no body" luckily.

```ruby
  store_with Dropbox do |db|
    db.chunk_size     = 1 # MiB
    db.max_retries    = 10
    db.retry_waitsec  = 30
  end
```

I ran it several times now, patched, unpatched, with all versions of the `upload` method as you posted above. They all work, they never get stuck.

I'd rather not have the dropbox ChunkedUploader `upload` method run a patch that's based on an earlier version of the gem. I don't see the big change that the patch should introduce. And I hope that if this was ever a problem it's been fixed since in the official gem. I hope.

So as far as I'm concerned we can remove the patch.
Agreed?

**Comment by tomash** [comment]
Agreed, I'll remove the patch from this PR.

**Comment by alex-ross** [comment]
@tomash and @tombruijn we have the exact same issue that this PR will fix. How is the status on this right now? We can help if none of you have time to fix any missing part in this PR.

But if I understand you correctly this works as is, but the dropbox patch should be removed because it's no longer necessary.

**Comment by tombruijn** [comment]
I'll merge this and remove the patch then. I'll go through the rest of the open issues before I release a new version. You can use the `master` branch in the meantime

**Pull request merged**
