### PR TITLE
Elasticsearch Database

### PR DESCRIPTION
**Pull request by portertech**
This adds a database: "Elasticsearch"

Currently supports tar'n all indices or a specific index (primary goal). I needed to backup yesterdays' Logstash index.

It can flush and/or close an index before backing it up, using the Elasticsearch API. This functionality is exposed via invoke_flush & invoke_close.

Example usage:

https://gist.github.com/portertech/c8cd4ccfa968256cd194

Please let me know your thoughts.

### CODE REVIEW

**Comment by mmzoo** [comment]
Newer versions of ES have an in-built [backup API](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/modules-snapshots.html) which don't require blocking the index during the backup. I think that should be taken into consideration before merging this solution.

**Comment by tombruijn** [comment]
I don't think I'll merge this until someone can take ownership of it and update it.

**Comment by seanfcarroll** [comment]
This would be handy

**Comment by portertech** [comment]
No longer using this. Not going to update this PR. Closing.

**Pull request closed without merging**
