### PR TITLE
Add ruby 2.5 to CI

### PR DESCRIPTION
**Pull request by dalpo**

### CODE REVIEW

**Comment by tombruijn** [comment]
Hi @dalpo !

Thanks for the Pull Request.

We should add Ruby 2.5 to the build, but I see there's some new output in the 2.5 build: https://travis-ci.org/backup/backup/jobs/355868989

For example:

```
#<Thread:0x000000000813c060@/home/travis/build/backup/backup/lib/backup/syncer/cloud/base.rb:94 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /home/travis/build/backup/backup/lib/backup/syncer/cloud/base.rb:95:in `block (2 levels) in sync_in_threads'
	4: from /home/travis/build/backup/backup/lib/backup/syncer/cloud/base.rb:95:in `loop'
	3: from /home/travis/build/backup/backup/lib/backup/syncer/cloud/base.rb:97:in `block (3 levels) in sync_in_threads'
	2: from /home/travis/build/backup/backup/lib/backup/syncer/cloud/base.rb:77:in `block in sync_directory'
	1: from /home/travis/build/backup/backup/lib/backup/syncer/cloud/base.rb:124:in `sync_file'
/home/travis/build/backup/backup/lib/backup/syncer/cloud/base.rb:132:in `rescue in sync_file': Syncer::Cloud::Error: Syncer Failed! (Backup::Syncer::Cloud::Error)
  See the Retry [info] and [error] messages (if any)
  for details on each failed operation.
```

We should probably look into why this is failing and fix it before merging.

**Comment by dalpo** [comment]
Hi @tombruijn!
You are right, I didn't notice these new warnings. I'll try to check them in the next days.

**Comment by dalpo** [comment]
Note: the issue is due to a ruby default changed in the latest version.
https://bugs.ruby-lang.org/issues/14143

**Comment by hiphapis** [comment]
Thanks @dalpo !!
Did u get any update?

**Comment by nynhex** [comment]
@tombruijn looks like CI passed, anything else we need to do?  Otherwise I'll merge.

Also, have we thought about testing against `2.5.1`?  I'll be happy to do a quick pr.

**Comment by tombruijn** [comment]
It would be nice if we could fix it. It looks a bit worrying in the 2.5 build right now.
I think it's broken for every Ruby version (hopefully only in the specs), 2.5 just logs it to the test output.
So we can merge this with the output, as long as we try and fix it after it's merged.

About 2.5.1, I'd prefer it if we test against the latest patch release than the `x.x.0` release. So let's update the version in `travis.yml`

**Comment by dalpo** [comment]
I updated the travis manifest with the latest rubies. 
But sadly currently I haven't enough spare time to work on this issue... At least for now

**Comment by tombruijn** [comment]
Updated PR to fix merge conflicts, but I think the issue of the warnings in the 2.5 build still remains.

**Comment by dalpo** [comment]
Closed by https://github.com/backup/backup/pull/938

**Pull request closed without merging**
